#!/usr/bin/env python3
"""Download IEEE OUI + Bluetooth SIG assigned-number lists and emit C tables.

Run from anywhere; writes components/VendorLookup/vendor_table.inc.
"""
from __future__ import annotations

import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "components" / "VendorLookup" / "vendor_table.inc"

OUI_URL = "https://standards-oui.ieee.org/oui/oui.csv"
CO_URL = ("https://bitbucket.org/bluetooth-SIG/public/raw/main/"
          "assigned_numbers/company_identifiers/company_identifiers.yaml")
SVC_URL = ("https://bitbucket.org/bluetooth-SIG/public/raw/main/"
           "assigned_numbers/uuids/service_uuids.yaml")
APPEAR_URL = ("https://bitbucket.org/bluetooth-SIG/public/raw/main/"
              "assigned_numbers/core/appearance_values.yaml")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "esp-vendor-lookup/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def sanitize(s: str) -> str:
    s = s.strip()
    # The Bluetooth SIG YAML quotes names that contain commas/colons (e.g.
    # "name: 'Apple, Inc.'"); the IEEE CSV is already unquoted by csv.reader. Strip
    # one matching pair of surrounding quotes so the lookups show the bare name.
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "'\"":
        s = s[1:-1].strip()
    s = re.sub(r"\s+", " ", s)
    return s.replace("\\", "\\\\").replace('"', '\\"')


def parse_oui(data: bytes) -> list[tuple[int, str]]:
    rows = []
    for line in csv.reader(io.StringIO(data.decode("utf-8", "replace"))):
        if len(line) < 3:
            continue
        reg, assign, org = line[0], line[1], line[2]
        if reg != "MA-L" or not re.fullmatch(r"[0-9A-Fa-f]{6}", assign or ""):
            continue
        name = sanitize(org)
        if name and name not in ("IEEE Registration Authority",):
            rows.append((int(assign, 16), name))
    return rows


def parse_company(data: bytes) -> list[tuple[int, str]]:
    rows = []
    value = None
    for line in data.decode("utf-8", "replace").splitlines():
        s = line.strip()
        if s.startswith("- value:"):
            value = int(s.split(":", 1)[1].strip(), 16)
        elif s.startswith("name:") and value is not None:
            name = sanitize(s.split(":", 1)[1])
            if name:
                rows.append((value, name))
            value = None
    return rows


def parse_service(data: bytes) -> list[tuple[int, str]]:
    """16-bit service UUIDs only; the 128-bit ones are custom and rarely advertised
    as such."""
    rows = []
    uuid = None
    for line in data.decode("utf-8", "replace").splitlines():
        s = line.strip()
        if s.startswith("- uuid:"):
            uuid = int(s.split(":", 1)[1].strip(), 16)
        elif s.startswith("name:") and uuid is not None:
            name = sanitize(s.split(":", 1)[1])
            if name and 0 <= uuid < 0x10000:
                rows.append((uuid, name))
            uuid = None
    return rows


def parse_appearance(data: bytes) -> list[tuple[int, str]]:
    """GAP appearance: category << 6 | subcategory. Each category alone is one entry;
    each subcategory is another."""
    rows = []
    cat = None
    cat_name = None
    pending_sub = None
    in_sub = False
    for line in data.decode("utf-8", "replace").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        s = line.strip()
        if s.startswith("- category:"):
            cat = int(s.split(":", 1)[1].strip(), 16)
            cat_name = None
            in_sub = False
            pending_sub = None
        elif s.startswith("name:") and cat is not None and not in_sub and cat_name is None:
            cat_name = sanitize(s.split(":", 1)[1])
            if cat_name:
                rows.append((cat << 6, cat_name))
        elif s.startswith("subcategory:"):
            in_sub = True
        elif in_sub and s.startswith("- value:"):
            pending_sub = int(s.split(":", 1)[1].strip(), 16)
        elif (in_sub and s.startswith("name:") and cat is not None and cat_name is not None
              and pending_sub is not None):
            sub_name = sanitize(s.split(":", 1)[1])
            if sub_name:
                rows.append(((cat << 6) | pending_sub, f"{cat_name} / {sub_name}"))
    return rows


def main() -> int:
    oui = parse_oui(fetch(OUI_URL))
    co = parse_company(fetch(CO_URL))
    svc = parse_service(fetch(SVC_URL))
    appearance = parse_appearance(fetch(APPEAR_URL))
    oui.sort()
    co.sort()
    svc.sort()
    appearance.sort()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/gen_vendor_table.py -- DO NOT EDIT. */\n")
        f.write("/* %d MA-L OUIs, %d BLE company IDs, %d service UUIDs, %d appearances. */\n"
                % (len(oui), len(co), len(svc), len(appearance)))
        f.write("typedef struct { uint32_t oui; const char *name; } vendor_oui_t;\n")
        f.write("typedef struct { uint16_t company; const char *name; } vendor_co_t;\n")
        f.write("typedef struct { uint16_t uuid; const char *name; } vendor_svc_t;\n")
        f.write("typedef struct { uint16_t appearance; const char *name; } vendor_appearance_t;\n\n")
        f.write("static const vendor_oui_t vendor_oui_table[] = {\n")
        for o, n in oui:
            f.write('    { 0x%06X, "%s" },\n' % (o, n))
        f.write("};\n")
        f.write("static const uint32_t vendor_oui_count = "
                "(uint32_t)(sizeof(vendor_oui_table) / sizeof(vendor_oui_table[0]));\n\n")
        f.write("static const vendor_co_t vendor_co_table[] = {\n")
        for c, n in co:
            f.write('    { 0x%04X, "%s" },\n' % (c, n))
        f.write("};\n")
        f.write("static const uint32_t vendor_co_count = "
                "(uint32_t)(sizeof(vendor_co_table) / sizeof(vendor_co_table[0]));\n\n")
        f.write("static const vendor_svc_t vendor_svc_table[] = {\n")
        for u, n in svc:
            f.write('    { 0x%04X, "%s" },\n' % (u, n))
        f.write("};\n")
        f.write("static const uint32_t vendor_svc_count = "
                "(uint32_t)(sizeof(vendor_svc_table) / sizeof(vendor_svc_table[0]));\n\n")
        f.write("static const vendor_appearance_t vendor_appearance_table[] = {\n")
        for a, n in appearance:
            f.write('    { 0x%04X, "%s" },\n' % (a, n))
        f.write("};\n")
        f.write("static const uint32_t vendor_appearance_count = "
                "(uint32_t)(sizeof(vendor_appearance_table) / sizeof(vendor_appearance_table[0]));\n")

    print("wrote %s: %d OUIs, %d companies, %d services, %d appearances"
          % (OUT, len(oui), len(co), len(svc), len(appearance)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
