#!/usr/bin/env python3
"""Download IEEE OUI + Bluetooth SIG company IDs and emit a C table for the firmware.

Run from anywhere; writes components/VendorLookup/vendor_table.inc.
"""
from __future__ import annotations

import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "components" / "VendorLookup" / "vendor_table.inc"

OUI_URL = "https://standards-oui.ieee.org/oui/oui.csv"
CO_URL = ("https://bitbucket.org/bluetooth-SIG/public/raw/main/"
          "assigned_numbers/company_identifiers/company_identifiers.yaml")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "esp-vendor-lookup/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def sanitize(s: str) -> str:
    s = re.sub(r"\s+", " ", s.strip())
    return s.replace("\\", "\\\\").replace('"', '\\"')


def parse_oui(data: bytes) -> list[tuple[int, str]]:
    rows = []
    for line in csv.reader(io.StringIO(data.decode("utf-8", "replace"))):
        if len(line) < 3:
            continue
        reg, assign, org = line[0], line[1], line[2]
        if reg != "MA-L" or not re.fullmatch(r"[0-9A-Fa-f]{6}", assign or ""):
            continue
        name = sanitize(org)
        if name and name not in ("IEEE Registration Authority",):
            rows.append((int(assign, 16), name))
    return rows


def parse_company(data: bytes) -> list[tuple[int, str]]:
    rows = []
    value = None
    for line in data.decode("utf-8", "replace").splitlines():
        s = line.strip()
        if s.startswith("- value:"):
            value = int(s.split(":", 1)[1].strip(), 16)
        elif s.startswith("name:") and value is not None:
            name = sanitize(s.split(":", 1)[1])
            if name:
                rows.append((value, name))
            value = None
    return rows


def main() -> int:
    oui = parse_oui(fetch(OUI_URL))
    co = parse_company(fetch(CO_URL))
    oui.sort()
    co.sort()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/gen_vendor_table.py -- DO NOT EDIT. */\n")
        f.write("/* %d MA-L OUIs, %d BLE company IDs. */\n" % (len(oui), len(co)))
        f.write("typedef struct { uint32_t oui; const char *name; } vendor_oui_t;\n")
        f.write("typedef struct { uint16_t company; const char *name; } vendor_co_t;\n\n")
        f.write("static const vendor_oui_t vendor_oui_table[] = {\n")
        for o, n in oui:
            f.write('    { 0x%06X, "%s" },\n' % (o, n))
        f.write("};\n")
        f.write("static const uint32_t vendor_oui_count = "
                "(uint32_t)(sizeof(vendor_oui_table) / sizeof(vendor_oui_table[0]));\n\n")
        f.write("static const vendor_co_t vendor_co_table[] = {\n")
        for c, n in co:
            f.write('    { 0x%04X, "%s" },\n' % (c, n))
        f.write("};\n")
        f.write("static const uint32_t vendor_co_count = "
                "(uint32_t)(sizeof(vendor_co_table) / sizeof(vendor_co_table[0]));\n")

    print("wrote %s: %d OUIs, %d companies" % (OUT, len(oui), len(co)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
